version: "3.2"
services:
 prometheus:
   image: prom/prometheus
   ports:
     - "9090:9090"
   volumes:
     - ./prometheus.yml:/etc/prometheus/prometheus.yml

 grafana:
   image: grafana/grafana
   ports:
     - "3000:3000"
   volumes:
     - ./grafana:/var/lib/grafana

 zookeeper:
   image: wurstmeister/zookeeper
   ports:
     - "2181:2181"

 kafka:
   build: .
   links:
     - zookeeper
   ports:
     - "9092:9092"
   expose:
     - "9093"
   environment:
     KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
     KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
     KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
     KAFKA_CREATE_TOPICS: "topic_test:1:1"
     KAFKA_ADVERTISED_PORT: 9092
     KAFKA_OPTS: -javaagent:/usr/app/jmx_prometheus_javaagent.jar=7071:/usr/app/broker-config.yml
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock