version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - 8002:8501
    volumes:
      - .:/app
    networks:
      default:
        ipv4_address: 172.22.0.8
networks:
  default:
    external: true
    name: kafka-docker_prod