version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - 8002:8501
    volumes:
      - .:/app
    environment:
      KAFKA_OPTS: -javaagent:/usr/app/jmx_prometheus_javaagent.jar=7071:/usr/app/consumer-config.yml

networks:
  default:
    external:
      name: kafka-docker_default