version: '3.8'
services:
  ytchats:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - 9000:9000
    volumes:
      - .:/app
    networks:
      default:
        ipv4_address: 172.22.0.6
networks:
  default:
    external: true
    name: kafka-docker_prod




