version: '3.8'
services:
  ytchats:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - 9000:9000
    volumes:
      - .:/app
networks:
  default:
    external: true
    name: kafka-docker_default
